language: php

php:
  - 5.3

mysql:
  database: zariz
  username: root
  encoding: utf8

before_script:
  # navigate out of module directory to prevent blown stack by recursive module lookup
  - cd ../..

  # install drush
  - pear channel-discover pear.drush.org
  - pear install drush/drush-5.8.0
  - phpenv rehash

  # install php packages required for running a web server from drush on php 5.3
  - sudo apt-get update > /dev/null
  - sudo apt-get install -y --force-yes php5-cgi php5-mysql

  # create new site, stubbing sendmail path with true to prevent delivery errors and manually resolving drush path
  - mysql -e 'create database zariz'
  - php -d sendmail_path=`which true` `pear config-get php_dir`/drush/drush.php --yes core-quick-drupal --profile=testing --no-server --db-url=mysql://root:@127.0.0.1/zariz --enable=simpletest zariz og_purl

  # reference and enable zariz in build site
  - ln -s $(readlink -e $(cd -)) zariz/drupal/sites/all/modules/zariz
  - cd zariz/drupal
  - drush dl og -y
  - drush en og_context og_purl -y
  # Hack to fix Replicate's module strict warning.
  - drush dl replicate
  - curl -O https://drupal.org/files/replicate-2098341-01-php-warning.patch
  - patch -p1 /home/travis/build/zariz/drupal/sites/all/modules/replicate/replicate.module < replicate-2098341-01-php-warning.patch
  - drush --yes pm-enable zariz

  # start a web server on port 8080, run in the background; wait for initialization
  - drush runserver 127.0.0.1:8080 &
  - until netstat -an 2>/dev/null | grep '8080.*LISTEN'; do true; done

script: drush test-run 'ZarizEntityReferenceUiTestCase' --uri=http://127.0.0.1:8080
